name: rtsp-types

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  rustfmt-clippy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install stable
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
        components: clippy, rustfmt

    - name: Run rustfmt
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: -- --check

    - name: Run clippy
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all-targets --all-features -- -D warnings

  ubuntu-tests:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        toolchain: ['1.58', stable, beta, nightly]

    steps:
    - uses: actions/checkout@v2

    - name: Install ${{ matrix.toolchain }}
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.toolchain }}
        override: true

    - name: Use MSRV Cargo.lock
      run: cp Cargo.lock.msrv Cargo.lock
      if: matrix.toolchain == '1.58'

    - name: Run tests
      run: |
        cargo test
